version: '3.7'
services:
  db:
    image: postgres:16-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - 5436:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  app:
    build:
      context: .
    container_name: app
    command: [ "/app/docker/app.sh" ]
    depends_on:
      db:
        condition: service_healthy
    restart: always

  funnel:
    build:
      context: .
    container_name: funnel
    command: [ "sh", "-c", "PYTHONPATH=$(pwd) python src/funnel.py" ]
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgresdata: